title: "Sehba's Portfolio Website"
url: "https://sehbaw.github.io"
# gem: "researcher"
#remote_theme: ankitsultana/researcher

markdown: kramdown

tracking_id: #


footer: yes
# footer_url: "https://github.com/sehbaw"
footer_text: "© Sehba Wani 2022"

sass:
    style: compressed
    sass_dir: _sass

